In [39]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [40]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [41]:
arquivo ='z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-04-19 02:19:23.044224
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-04-19 02:19:23.044224
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-04-19 02:19:23.044224

In [42]:
con.execute("""
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,   
        WERKS VARCHAR,    
        MAINS VARCHAR,    
        LABST VARCHAR,    
        nome_arquivo VARCHAR,    
        data_ingestao TIMESTAMP             
    )
""")

In [43]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [46]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetchdf()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-04-19 01:50:25.826680
1  10002   MARTELO  BT50   100   100  z0019_1.csv 2026-04-19 01:50:25.826680
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-04-19 01:50:25.826680
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-04-19 02:07:09.725428
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-04-19 02:07:09.725428
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-04-19 02:07:09.725428

In [48]:
con.close()